channels:
  sources:
    - scikit-xray-dev
  target: scikit-xray-dev
docker:
  image: pelson/obvious-ci:latest_x64
templates:
  run_docker_build: run_docker_build_matrix.tmpl
matrix:
  python:
    - 2.7
    - 3.4
  numpy:
    - 1.9
